## completion engine

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
source ~/.config/nvim/plugins/deoplete.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
hook_add = '''
imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)
let g:neosnippet#enable_snipmate_compatibility = 1
let g:neosnippet#enable_completed_snippet = 1
let g:neosnippet#expand_word_boundary = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

## html

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'vue']
hook_add = '''
let g:user_emmet_leader_key = '<c-a>'
'''
